posts/urls.py
from django.conf.urls import url
from posts import views

urlpatterns = [
    url(r'^create/$', views.post_create, name="create"),
    url(r'^list/$', views.post_list, name="list"),
    url(r'^detail/(?P<post_slug>[-\w]+)/$', views.post_detail, name="detail"),
	url(r'^update/(?P<post_slug>[-\w]+)/$', views.post_update, name="update"),
    url(r'^delete/(?P<post_slug>[-\w]+)/$', views.post_delete, name="delete"),
    url(r'^ajax_like/(?P<post_id>\d+)/$', views.ajax_like, name="like_button"),
    url(r'^signup/$', views.usersignup, name="signup"),
url(r'^login/$', views.userlogin, name="login"),
url(r'^logout/$', views.userlogout, name="logout"),
]

tasks_blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^posts/', include('posts.urls', namespace="posts")),
]

if settings.DEBUG:
	urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.db.models.signals import pre_save
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
	author = models.ForeignKey(User, default=1)
	title = models.CharField(max_length=255)
	content = models.TextField()
	draft = models.BooleanField(default=False)
	publish = models.DateField(auto_now=False, auto_now_add=False)
	slug = models.SlugField(unique=True)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
	image = models.ImageField(upload_to="blog_images", null=True, blank=True)

def __str__(self):
	return self.title

def get_absolute_url(self):
		return reverse("posts:detail", kwargs={"post_slug": self.slug})

class Meta:
		ordering = ["-timestamp", "-updated"]

def create_slug(instance, new_slug=None):
    slug = slugify (instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s"%(slug,qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_reciever(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug=create_slug(instance)

pre_save.connect(pre_save_post_reciever,sender=Post)

class Like(models.Model):
    user = models.ForeignKey(User)
    post = models.ForeignKey(Post)
    created = models.DateTimeField(auto_now_add=True)

posts/forms.py
from django import forms
from .models import Post
from django.contrib.auth.models import User

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'image', 'draft', 'publish']

       	widgets={
        'publish': forms.DateInput(attrs={"type":"date"}),
        }

class UserSignup(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','password']

        widgets={
        'password': forms.PasswordInput(),
        }

class UserLogin(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, widget=forms.PasswordInput())

posts/views.py
from django.http import HttpResponse, Http404, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Like
from .forms import PostForm
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import timezone
from django.db.models import Q
from .forms import UserSignup, UserLogin
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def post_create(request):
	if not (request.user.is_staff or request.user.is_superuser):
		return render(request, 'restricted_access.html')
	form = PostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		post = form.save(commit = False)
		post.author = request.user
		post.save()
		messages.success(request, "Successfully Created!")
		return redirect("posts:list")
	context={
	"title": "Create",
	"form": form,
	}
	return render(request, 'post_create.html', context)

def post_list(request):
	today = timezone.now().date()
	object_list = Post.objects.filter(draft=False).filter(publish__lte=today)
	if request.user.is_staff or request.user.is_superuser:
		object_list = Post.objects.all().order_by("-timestamp","-updated")

	query = request.GET.get("q")
	if query:
		object_list = object_list.filter(
			Q(title__icontains=query)|
			Q(content__icontains=query)|
			Q(author__first_name__icontains=query)|
			Q(author__last_name__icontains=query)
			).distinct()

	paginator = Paginator(object_list, 4)
	page = request.GET.get('page')
	try:
		objects = paginator.page(page)
	except PageNotAnInteger:
		objects = paginator.page(1)
	except EmptyPage:
		objects = paginator.page(paginator.num_pages)
	context = {
	"object_list": objects,
	"title": "List",
	"user": request.user,
	"today": today,
	}
	return render(request, 'post_list.html', context)

def post_detail(request, post_slug):
	instance = get_object_or_404(Post, slug=post_slug)

	if instance.publish>timezone.now().date() or instance.draft:
		if not (request.user.is_staff or request.user.is_superuser):
			return render(request, 'restricted_access.html')

	if request.user.is_authenticated():
		if Like.objects.filter(post=instance, user=request.user).exists():
			liked = True
		else:
			liked = False

	context = {
	"title": "Detail",
	"instance": instance,
	"liked":liked,
	}
	return render(request, 'post_detail.html', context)

def post_update(request, post_slug):
	if not (request.user.is_staff or request.user.is_superuser):
		return render(request, 'restricted_access.html')
	post_object = get_object_or_404(Post, slug=post_slug)
	form = PostForm(request.POST or None, request.FILES or None, instance = post_object) 
	if form.is_valid():
		form.save()
		messages.success(request, "Changes Saved")
		return redirect("posts:list")
	context = {
	'title':'Update',
	'user': request.user,
	'form': form,
	'post_object': post_object,
	}
	return render(request, 'post_update.html', context)

def post_delete(request, post_slug):
	if not (request.user.is_staff or request.user.is_superuser):
		return render(request, 'restricted_access.html')
	instance = get_object_or_404(Post, slug=post_slug)
	instance.delete()
	messages.success(request, "Successfully Deleted!")
	return redirect("posts:list")

def ajax_like(request, post_id):
	post_object = Post.objects.get(id=post_id)
	new_like, created = Like.objects.get_or_create(user=request.user, post=post_object)

	if created:
		action="like"
	else:
		new_like.delete()
		action="unlike"

	post_like_count = post_object.like_set.all().count()
	response = {
		"action": action,
		"post_like_count": post_like_count,
	}
	return JsonResponse(response, safe=False)

def usersignup(request):
    context = {}
    form = UserSignup()
    context['form'] = form
    if request.method == 'POST':
        form = UserSignup(request.POST)
        if form.is_valid():
            user = form.save()
            username = user.username
            password = user.password

            user.set_password(password)
            user.save()

            auth_user = authenticate(username=username, password=password)
            login(request, auth_user)

            return redirect("posts:list")
        messages.error(request, form.errors)
        return redirect("posts:signup")
    return render(request, 'signup.html', context)

def userlogin(request):
    context = {}
    form = UserLogin()
    context['form'] = form
    if request.method == 'POST':
        form = UserLogin(request.POST)
        if form.is_valid():

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            auth_user = authenticate(username=username, password=password)
            if auth_user is not None:
                login(request, auth_user)
                return redirect('posts:list')

            messages.error(request, "Wrong username/password combination. Please try again.")
            return redirect("posts:login")
        messages.error(request, form.errors)
        return redirect("posts:login")
    return render(request, 'login.html', context)

def userlogout(request):
    logout(request)
    messages.success(request, "Sorry to see you go.")
    return redirect("posts:list")

posts/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Post {{title}}</title>
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
	{% include "facebook_comments.html" %}
	{% include "navbar.html" %}
	{% include 'messages.html'%}
	
	<div class = "container">
		{% block content %}
		{% endblock content %}
	</div>
	<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

posts/templates/facebook_comments.html
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.9";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

posts/templates/likes.html
<button class="btn" onclick="ajax_like()">
	<span id="likes_count">{{post_like_count}}</span>
	<span id= "heart" class="glyphicon glyphicon-heart {% if liked %}text-danger{% endif %}" aria-hidden="true"></span>
</button>

<script type="text/javascript">
	function ajax_like() {
		console.log("Like/Unlike clicked!");
		$.ajax({
			   type:'GET',
				url: '{% url "posts:like_button" post_id=instance.id %}',
				error: function(){
					console.log('error');
				},
				success: function(data){ 
					$("#likes_count").text(data.post_like_count);

					if(data.action==="like"){
						$("#heart").addClass("text-danger");
					}else{
						$("#heart").removeClass("text-danger")  
					}
				}
			}	
		);
	}
</script>

posts/templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
Login
{% endblock title %}


{% block content %}
    <form action="{% url 'posts:login' %}" method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input class = "btn btn-primary" type="submit" value="Login">
    </form>
{% endblock content %}

posts/templates/messages.html
{% if messages%}
	<ul>
	{%for message in messages%}
		<li>{{message}}</li>
	{% endfor %}
	</ul>
{% endif %}

posts/templates/navbar.html
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'posts:list' %}">Django Blog</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'posts:list' %}">Posts List</a></li>
        <li><a href="{% url 'posts:create' %}">Create Post</a></li>
      </ul>
      <form class="navbar-form navbar-left" action="" method="GET">
        <div class="form-group">
          <input type="text" class="form-control" name="q" placeholder="Search" value="{{request.GET.q}}">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        {% if request.user.is_authenticated %}
          <li><a href="#">{{request.user}}</a></li>
          <li><a href="{% url 'posts:logout' %}">Logout</a></li>
        {% else %}
          <li><a href="{% url 'posts:login' %}">Login</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

posts/templates/post_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

	{% block content %}
		<form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{form|crispy}}
			<input type="submit" value="Create Post">
		</form>
	{% endblock content %}

posts/templates/post_detail.html
{% extends "base.html" %}
{% load urlify %}
	{% block content %}

		<div class="row">
			<div class="col-sm-6">
				<div class="thumbnail">
					{% if instance.image %}
						<img src="{{instance.image.url}}" alt="nothing">
					{% endif %}
				  <div class="caption">
					<h3>{{instance.title}}</h3>
					<p>{{instance.content|linebreaks}}</p>
					<p>Last edited: {{instance.updated|timesince}} ago</p>
					<p>Published: {{instance.publish|timesince}} ago</p>
					<p>Created: {{instance.timestamp|timesince}} ago</p>
					<p>Author: {{instance.author}}</p>

					<a href="{% url 'posts:list' %}" class="btn btn-default" role="button">Back to list</a>
					<a href="{% url 'posts:update' post_slug=instance.slug %}" class="btn btn-warning" role="button">Edit</a>
					<a href="{% url 'posts:delete' post_slug=instance.slug %}" class="btn btn-danger" role="button">Delete</a>
					
					{% include "likes.html" %}
	
					<p><a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}">Share on Facebook</a></p>

			        <p><a href="https://twitter.com/home?status={{instance.content|truncatechars:35|urlify}}%20{{request.build_absolute_uri}}">Share on Twitter</a></p>

			        <p><a href="https://www.linkedin.com/shareArticle?mini=true&url={{request.build_absolute_uri}}&title={{instance.title|urlify}}&summary={{instance.content|truncatechars:35|urlify}}&source={{request.build_absolute_uri}}">
			        Share on Linkedin
			        </a></p>

				  </div>
				</div>
			</div>
		</div>

		<div class="fb-like" data-href="{{request.build_absolute_uri}}" data-layout="button_count" data-action="like" data-size="large" data-show-faces="true" data-share="true"></div>
		<div class="fb-comments" data-href="{{request.build_absolute_uri}}" data-numposts="5"></div>

	{% endblock content %}


	

posts/templates/post_list.html
{% extends "base.html" %}

{% block content %}
	<div class="row">
		{% for object in object_list %}
			  <div class="col-sm-6">
				<div class="thumbnail">
					{% if object.image %}
						<img src="{{object.image.url}}" alt="nothing">
					{% endif %}
				  <div class="caption">
					<h3><a href="{% url 'posts:detail' post_slug=object.slug %}">{{object.title}}</a> <small>{{object.publish}}</small></h3>
					<p>{{object.content|truncatechars:10}}</p>

					{% if object.draft %}<h3>Draft</h3>{% endif %}

       				{% if object.publish > today %}<h3>Future Post</h3>{% endif %}

					<a href="{% url 'posts:detail' post_slug=object.slug %}" class="btn btn-primary" role="button">Details</a>
					<a href="{% url 'posts:update' post_slug=object.slug %}" class="btn btn-warning" role="button">Edit</a>
					<a href="{% url 'posts:delete' post_slug=object.slug %}" class="btn btn-danger" role="button">Delete</a>
				  </div>
				</div>
			  </div>
		{% endfor %}
	</div>	

	<a href="{% url 'posts:create' %}">Create Post</a><br>

	 <div class="pagination">
		<span class="step-links">
			{% if object_list.has_previous %}
				<a href="?page={{ object_list.previous_page_number }}&q={{ request.GET.q }}">previous</a>
			{% endif %}

			<span class="current">
				Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
			</span>

			{% if object_list.has_next %}
				<a href="?page={{ object_list.next_page_number }}&q={{ request.GET.q }}">next</a>
			{% endif %}
		</span>
	</div>
{% endblock content %}

posts/templates/post_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

	{% block content %}
		<form action="{% url 'posts:update' post_slug=post_object.slug %}" method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{form.crispy}}
			<input type="submit" value="Update Post">
		</form>
	{% endblock content %}

posts/templates/restricted_access.html
{% extends "base.html" %}
	{% block content%}

		<h2>You do NOT have Permission to do that.</h2>
		<h3>Shame on you. Go stand in the corner.</h3>

	{% endblock content%}

posts/templates/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
Sign Up
{% endblock title %}


{% block content %}
    <form action="{% url 'posts:signup' %}" method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input class = "btn btn-primary" type="submit" value="Sign Up">
    </form>
{% endblock content %}